spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost/camunda
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update



camunda.bpm:

  admin-user:
    id: demo
    password: demo
    firstName: Demo

  authorization:
    enabled: true

server:
  port: 8080


key.regEnabled: True



logging:
  level:
    com:
      baeldung: INFO
    root: INFO